/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.clients.views;

import app.clients.controller.ClientController;
import app.clients.dto.ClientSummaryDTO;
import app.clients.model.Client;
import app.clients.exceptions.ClientValidationException;
import app.utils.db.DBException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eldair
 */
public class ClientView extends javax.swing.JFrame {

    ClientController controller;

    public ClientView() {
        try {
            this.controller = new ClientController();
        } catch (DBException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        initComponents();
        loadClients();
    }

    /**
     * Creates new form ClientView
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tp_clientTabs = new javax.swing.JTabbedPane();
        pn_clients = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txt_nameToSearch = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_clients = new javax.swing.JTable();
        btn_viewClient = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_newClient_tab1 = new javax.swing.JButton();
        btn_refreshTable = new javax.swing.JButton();
        pn_clientData = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_homePhone = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_cellPhone = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_number = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txt_neighborhood = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_zipCode = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        cbx_uf = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_newClient_tab2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/utils/images/customers.png"))); // NOI18N
        jLabel1.setText(" Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_clientTabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tp_clientTabs.setMaximumSize(new java.awt.Dimension(800, 400));
        tp_clientTabs.setMinimumSize(new java.awt.Dimension(800, 400));
        tp_clientTabs.setPreferredSize(new java.awt.Dimension(800, 400));

        pn_clients.setBackground(new java.awt.Color(255, 255, 255));
        pn_clients.setMaximumSize(new java.awt.Dimension(777, 335));
        pn_clients.setMinimumSize(new java.awt.Dimension(777, 335));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Nome:");

        txt_nameToSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_search.setText("Pesquisar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        tb_clients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "E-mail", "Telefone", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_clients.setRowHeight(25);
        jScrollPane1.setViewportView(tb_clients);
        if (tb_clients.getColumnModel().getColumnCount() > 0) {
            tb_clients.getColumnModel().getColumn(0).setResizable(false);
            tb_clients.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_clients.getColumnModel().getColumn(0).setHeaderValue("Código");
            tb_clients.getColumnModel().getColumn(1).setResizable(false);
            tb_clients.getColumnModel().getColumn(1).setPreferredWidth(200);
            tb_clients.getColumnModel().getColumn(1).setHeaderValue("Nome");
            tb_clients.getColumnModel().getColumn(2).setResizable(false);
            tb_clients.getColumnModel().getColumn(2).setPreferredWidth(100);
            tb_clients.getColumnModel().getColumn(2).setHeaderValue("CPF");
            tb_clients.getColumnModel().getColumn(3).setResizable(false);
            tb_clients.getColumnModel().getColumn(3).setPreferredWidth(200);
            tb_clients.getColumnModel().getColumn(3).setHeaderValue("E-mail");
            tb_clients.getColumnModel().getColumn(4).setResizable(false);
            tb_clients.getColumnModel().getColumn(4).setPreferredWidth(100);
            tb_clients.getColumnModel().getColumn(4).setHeaderValue("Telefone");
            tb_clients.getColumnModel().getColumn(5).setResizable(false);
            tb_clients.getColumnModel().getColumn(5).setPreferredWidth(100);
            tb_clients.getColumnModel().getColumn(5).setHeaderValue("Celular");
        }

        btn_viewClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_viewClient.setText("Visualizar");
        btn_viewClient.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_viewClient.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_viewClient.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_viewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewClientActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_delete.setText("Excluir");
        btn_delete.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_delete.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_delete.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_newClient_tab1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_newClient_tab1.setText("Novo");
        btn_newClient_tab1.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab1.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab1.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newClient_tab1ActionPerformed(evt);
            }
        });

        btn_refreshTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_refreshTable.setText("Atualizar Tabela");
        btn_refreshTable.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_refreshTable.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_refreshTable.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_clientsLayout = new javax.swing.GroupLayout(pn_clients);
        pn_clients.setLayout(pn_clientsLayout);
        pn_clientsLayout.setHorizontalGroup(
            pn_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pn_clientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_clientsLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txt_nameToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_viewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pn_clientsLayout.createSequentialGroup()
                        .addComponent(btn_refreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_newClient_tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        pn_clientsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_delete, btn_newClient_tab1});

        pn_clientsLayout.setVerticalGroup(
            pn_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pn_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel33)
                    .addComponent(txt_nameToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search)
                    .addComponent(btn_viewClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_newClient_tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tp_clientTabs.addTab("Consulta de clientes", pn_clients);

        pn_clientData.setBackground(new java.awt.Color(255, 255, 255));
        pn_clientData.setMaximumSize(new java.awt.Dimension(750, 35));
        pn_clientData.setMinimumSize(new java.awt.Dimension(750, 35));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(750, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(750, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(750, 322));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(750, 35));
        jPanel10.setMinimumSize(new java.awt.Dimension(750, 35));
        jPanel10.setPreferredSize(new java.awt.Dimension(758, 35));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Código:");
        jLabel22.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel22.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel22.setPreferredSize(new java.awt.Dimension(65, 20));

        txt_code.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_code.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMaximumSize(new java.awt.Dimension(680, 35));
        jPanel13.setMinimumSize(new java.awt.Dimension(680, 35));
        jPanel13.setPreferredSize(new java.awt.Dimension(680, 36));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Nome:");
        jLabel34.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel34.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel34.setPreferredSize(new java.awt.Dimension(65, 20));

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_name.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMaximumSize(new java.awt.Dimension(680, 35));
        jPanel16.setMinimumSize(new java.awt.Dimension(680, 35));
        jPanel16.setPreferredSize(new java.awt.Dimension(680, 35));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("CPF:");
        jLabel41.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel41.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel41.setPreferredSize(new java.awt.Dimension(65, 20));

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setEnabled(false);
        txt_cpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Telefone (fixo):");

        try {
            txt_homePhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_homePhone.setEnabled(false);
        txt_homePhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Celular:");

        try {
            txt_cellPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cellPhone.setEnabled(false);
        txt_cellPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(txt_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(txt_cellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(750, 35));
        jPanel8.setMinimumSize(new java.awt.Dimension(750, 35));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("E-mail:");
        jLabel26.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel26.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel26.setPreferredSize(new java.awt.Dimension(65, 20));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMaximumSize(new java.awt.Dimension(750, 35));
        jPanel14.setMinimumSize(new java.awt.Dimension(750, 35));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Endereço:");
        jLabel23.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel23.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel23.setPreferredSize(new java.awt.Dimension(65, 20));

        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_address.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Nº:");

        txt_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_number.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(5, 5, 5))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMaximumSize(new java.awt.Dimension(680, 35));
        jPanel17.setMinimumSize(new java.awt.Dimension(680, 35));
        jPanel17.setPreferredSize(new java.awt.Dimension(680, 35));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Bairro:");
        jLabel43.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel43.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel43.setPreferredSize(new java.awt.Dimension(65, 20));

        txt_neighborhood.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_neighborhood.setEnabled(false);
        txt_neighborhood.setMaximumSize(new java.awt.Dimension(200, 26));
        txt_neighborhood.setMinimumSize(new java.awt.Dimension(200, 26));
        txt_neighborhood.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Cidade:");

        txt_city.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_city.setEnabled(false);
        txt_city.setMaximumSize(new java.awt.Dimension(64, 2147483647));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_neighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_neighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setMaximumSize(new java.awt.Dimension(680, 35));
        jPanel15.setMinimumSize(new java.awt.Dimension(680, 35));
        jPanel15.setPreferredSize(new java.awt.Dimension(680, 35));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("CEP:");

        try {
            txt_zipCode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_zipCode.setEnabled(false);
        txt_zipCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("UF:");
        jLabel39.setMaximumSize(new java.awt.Dimension(65, 20));
        jLabel39.setMinimumSize(new java.awt.Dimension(65, 20));
        jLabel39.setPreferredSize(new java.awt.Dimension(65, 20));

        cbx_uf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbx_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbx_uf.setEnabled(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btn_save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_save.setText("Salvar");
        btn_save.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_save.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_save.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_edit.setText("Editar");
        btn_edit.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_edit.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_edit.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_newClient_tab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_newClient_tab2.setText("Novo");
        btn_newClient_tab2.setMaximumSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab2.setMinimumSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab2.setPreferredSize(new java.awt.Dimension(90, 27));
        btn_newClient_tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newClient_tab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_clientDataLayout = new javax.swing.GroupLayout(pn_clientData);
        pn_clientData.setLayout(pn_clientDataLayout);
        pn_clientDataLayout.setHorizontalGroup(
            pn_clientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientDataLayout.createSequentialGroup()
                .addGroup(pn_clientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_clientDataLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_newClient_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(462, 462, 462)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_clientDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        pn_clientDataLayout.setVerticalGroup(
            pn_clientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientDataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pn_clientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_newClient_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tp_clientTabs.addTab("Dados pessoais", pn_clientData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 11, Short.MAX_VALUE)
                .addComponent(tp_clientTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tp_clientTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        String id = txt_code.getText();
        if (!id.isEmpty()) {
            enableClienTextfields();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi selecionado nenhum registro para ser editado");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            String code = txt_code.getText();
            String name = txt_name.getText();
            String cpf = txt_cpf.getText().replaceAll("[\\.\\-]", "");
            String email = txt_email.getText();
            String homePhone = txt_homePhone.getText().replaceAll("[\\s\\-()]", "");
            String cellPhone = txt_cellPhone.getText().replaceAll("[\\s\\-()]", "");
            String address = txt_address.getText();
            String zipCode = txt_zipCode.getText().replaceAll("[\\-]", "");
            String addressNumber = txt_number.getText();
            String neighborhood = txt_neighborhood.getText();
            String city = txt_city.getText();
            String uf = cbx_uf.getSelectedItem().toString();

            if (code.isEmpty()) {
                controller.createClient(name, cpf, email, homePhone, cellPhone, zipCode, address, addressNumber, neighborhood, city, uf);
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
            } else {
                controller.updateClient(Integer.parseInt(code), name, cpf, email, homePhone, cellPhone, zipCode, address, addressNumber, neighborhood, city, uf);
                JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");
            }
            
            disableClientTextFields();
            loadClients();

        } catch (DBException | ClientValidationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newClient_tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newClient_tab2ActionPerformed
        clearClientTextFields();
        enableClienTextfields();
    }//GEN-LAST:event_btn_newClient_tab2ActionPerformed

    private void btn_refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshTableActionPerformed

        loadClients();

    }//GEN-LAST:event_btn_refreshTableActionPerformed

    private void loadClients() {
        DefaultTableModel model = (DefaultTableModel) tb_clients.getModel();
        model.setRowCount(0);
        try {
            List<ClientSummaryDTO> clients = controller.getAllSummarizedClient();

            for (ClientSummaryDTO client : clients) {
                model.addRow(new Object[]{
                    client.id(), client.name(), client.cpf(), client.email(), client.homePhone(), client.cellPhone()
                });
            }
        } catch (DBException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        DefaultTableModel model = (DefaultTableModel) tb_clients.getModel();
        model.setRowCount(0);
        String name = txt_nameToSearch.getText();

        try {
            List<ClientSummaryDTO> clients = controller.getSummarizedClientsByName(name);
            for (ClientSummaryDTO client : clients) {
                model.addRow(new Object[]{
                    client.id(), client.name(), client.cpf(), client.email(), client.homePhone(), client.cellPhone()
                });
            }
        } catch (DBException | ClientValidationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_viewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewClientActionPerformed

        try {
            int line = tb_clients.getSelectedRow();
            if (line < 0) {
                throw new IllegalArgumentException("Selecione uma registro para visualizar!");
            }

            String id = tb_clients.getValueAt(line, 0).toString();

            Client client = controller.getById(id);
            if (client == null) {
                throw new ClientValidationException("Client não encontrado");
            }

            tp_clientTabs.setSelectedIndex(1);

            txt_code.setText("" + client.getId());
            txt_name.setText(client.getName());
            txt_cpf.setText(client.getCpf());
            txt_email.setText(client.getEmail());
            txt_homePhone.setText(client.getHomePhone());
            txt_cellPhone.setText(client.getCellPhone());
            txt_address.setText(client.getAddress());
            txt_zipCode.setText(client.getZipCode());
            txt_number.setText("" + client.getNumber());
            txt_neighborhood.setText(client.getNeighborhood());
            txt_city.setText(client.getCity());
            cbx_uf.setSelectedItem(client.getUf());

            disableClientTextFields();

        } catch (DBException | ClientValidationException | IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_btn_viewClientActionPerformed

    private void btn_newClient_tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newClient_tab1ActionPerformed

        tp_clientTabs.setSelectedIndex(1);

        clearClientTextFields();

        enableClienTextfields();
    }//GEN-LAST:event_btn_newClient_tab1ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            int line = tb_clients.getSelectedRow();
            if (line < 0) {
                throw new IllegalArgumentException("Selecione uma registro para visualizar!");
            }

            String id = tb_clients.getValueAt(line, 0).toString();
            String name = tb_clients.getValueAt(line, 1).toString();

            controller.deleteClientById(id);

            JOptionPane.showMessageDialog(null, "Cliente " + name + " foi excluido da tabela clientes");

        } catch (DBException | IllegalArgumentException | ClientValidationException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void enableClienTextfields() {
        txt_name.setEnabled(true);
        txt_cpf.setEnabled(true);
        txt_email.setEnabled(true);
        txt_homePhone.setEnabled(true);
        txt_cellPhone.setEnabled(true);
        txt_address.setEnabled(true);
        txt_zipCode.setEnabled(true);
        txt_number.setEnabled(true);
        txt_neighborhood.setEnabled(true);
        txt_city.setEnabled(true);
        cbx_uf.setEnabled(true);
    }

    private void disableClientTextFields() {
        txt_code.setEnabled(false);
        txt_name.setEnabled(false);
        txt_cpf.setEnabled(false);
        txt_email.setEnabled(false);
        txt_homePhone.setEnabled(false);
        txt_cellPhone.setEnabled(false);
        txt_address.setEnabled(false);
        txt_zipCode.setEnabled(false);
        txt_number.setEnabled(false);
        txt_neighborhood.setEnabled(false);
        txt_city.setEnabled(false);
        cbx_uf.setEnabled(false);
    }

    private void clearClientTextFields() {
        txt_code.setText("");
        txt_name.setText("");
        txt_cpf.setText("");
        txt_email.setText("");
        txt_homePhone.setText("");
        txt_cellPhone.setText("");
        txt_address.setText("");
        txt_zipCode.setText("");
        txt_number.setText("");
        txt_neighborhood.setText("");
        txt_city.setText("");
        cbx_uf.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_newClient_tab1;
    private javax.swing.JButton btn_newClient_tab2;
    private javax.swing.JButton btn_refreshTable;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_viewClient;
    private javax.swing.JComboBox<String> cbx_uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_clientData;
    private javax.swing.JPanel pn_clients;
    private javax.swing.JTable tb_clients;
    private javax.swing.JTabbedPane tp_clientTabs;
    private javax.swing.JTextField txt_address;
    private javax.swing.JFormattedTextField txt_cellPhone;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_code;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JFormattedTextField txt_homePhone;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nameToSearch;
    private javax.swing.JTextField txt_neighborhood;
    private javax.swing.JTextField txt_number;
    private javax.swing.JFormattedTextField txt_zipCode;
    // End of variables declaration//GEN-END:variables
}
